[alembic]
script_location = f22_system/backend/database/migrations
sqlalchemy.url = postgresql+asyncpg://user:password@localhost/dbname

[post_hooks]
python_file = f22_system/backend/database/post_hooks.py
